version: "3"
services:
  core:
    container_name: splitly-core
    image: splitly-core:latest
    networks: [sp-net]
    profiles:
      - splitly
    ports:
      - 48080:8080

  ui:
    container_name: splitly-ui
    image: splitly-ui:latest
    networks: [sp-net]
    profiles:
      - splitly
    ports:
      - 7001:3000
    environment: 
      NUXT_PUBLIC_SERVER_URL: http://localhost:48080

networks:
  sp-net:
    name: splitly-network
    driver: bridge
